# General Configuration
title: Communicating IT Inc.
email: ""
description: Deliver your most complex outcomes successfully!
baseurl: ""
url: "https://commit.ca"
social_image: "/assets/media/logo.svg"
keywords: ""
site-author: "Commit"
copyright: "2017 Commit"
google_analytics_id: "G-7D5ETBXWCH"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap

#Excluded Files
exclude: ["vendor",
          "_assets",
          "Gemfile",
          "Gemfile.lock",
          "gulpfile.js",
          "node_modules",
          "icons",
          "package.json",
          "package-lock.json",
          "README.md",
          "LICENSE.txt",
          "js",
          "css",
          "webpack.config.js",
          "webpack.build.config.js"
          ]
